import { defineConfig } from 'vitest/config'
import react from '@vitejs/plugin-react'
import { createHash } from 'node:crypto'
import { execFileSync } from 'node:child_process'
import { readdir, readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'

async function listFiles(directory: string, root = directory): Promise<string[]> {
  const entries = await readdir(directory, { withFileTypes: true })
  const files = await Promise.all(
    entries.map(async (entry) => {
      const absolutePath = path.join(directory, entry.name)
      return entry.isDirectory() ? listFiles(absolutePath, root) : [path.relative(root, absolutePath)]
    }),
  )

  return files.flat().sort()
}

function sourceBuildId(): string {
  const supplied = process.env.ARGUS_BUILD_SHA ?? process.env.GITHUB_SHA
  if (supplied) return supplied.slice(0, 7)

  try {
    return execFileSync('git', ['rev-parse', '--short=7', 'HEAD'], {
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore'],
    }).trim()
  } catch {
    return 'unknown'
  }
}

function serviceWorkerPlugin() {
  return {
    name: 'argus-service-worker',
    apply: 'build' as const,
    async closeBundle() {
      const outputDirectory = path.resolve('dist')
      const files = (await listFiles(outputDirectory)).filter((file) => file !== 'sw.js')
      const revision = createHash('sha256')

      for (const file of files) {
        revision.update(file)
        revision.update(await readFile(path.join(outputDirectory, file)))
      }

      const buildId = revision.digest('hex').slice(0, 16)
      const precacheUrls = files.map((file) => `/${file}`)
      const source = `// Generated by vite.config.ts. Do not edit dist/sw.js directly.
const CACHE_PREFIX = 'argus-app-'
const CACHE_NAME = CACHE_PREFIX + ${JSON.stringify(buildId)}
const LEGACY_CACHE_NAMES = new Set(['argus-v1'])
const PRECACHE_URLS = ${JSON.stringify(precacheUrls, null, 2)}
const FALLBACK_URL = '/index.html'

const cacheResponse = async (cache, request, response) => {
  if (response.ok && (response.type === 'basic' || response.type === 'default')) {
    await cache.put(request, response.clone())
  }
  return response
}

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => cache.addAll(PRECACHE_URLS)),
  )
  self.skipWaiting()
})

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(
        keys
          .filter((key) =>
            (key.startsWith(CACHE_PREFIX) && key !== CACHE_NAME) || LEGACY_CACHE_NAMES.has(key),
          )
          .map((key) => caches.delete(key)),
      ))
      .then(() => self.clients.claim()),
  )
})

self.addEventListener('message', (event) => {
  if (event.data?.type === 'SKIP_WAITING') self.skipWaiting()
})

self.addEventListener('fetch', (event) => {
  const request = event.request
  if (request.method !== 'GET') return

  const url = new URL(request.url)
  if (url.origin !== self.location.origin) return

  if (request.mode === 'navigate') {
    event.respondWith(
      caches.open(CACHE_NAME).then(async (cache) => {
        try {
          const response = await fetch(request, { cache: 'no-store' })
          return cacheResponse(cache, FALLBACK_URL, response)
        } catch {
          return (await cache.match(FALLBACK_URL)) || Response.error()
        }
      }),
    )
    return
  }

  if (url.pathname.startsWith('/assets/')) {
    event.respondWith(
      caches.match(request).then((cached) => cached || fetch(request)),
    )
    return
  }

  event.respondWith(
    caches.open(CACHE_NAME).then(async (cache) => {
      try {
        const response = await fetch(request, { cache: 'no-store' })
        return cacheResponse(cache, request, response)
      } catch {
        return (await cache.match(request)) || Response.error()
      }
    }),
  )
})
`

      await writeFile(path.join(outputDirectory, 'sw.js'), source)
    },
  }
}

export default defineConfig({
  define: {
    __ARGUS_BUILD_ID__: JSON.stringify(sourceBuildId()),
  },
  plugins: [react(), serviceWorkerPlugin()],
  // Firebase Hosting is the sole deployment target, serving from the root of
  // its own domain. GitHub Pages is retired.
  base: '/',
  test: {
    // The Security Rules suite needs a live Firestore emulator, so it runs
    // under its own config rather than in the ordinary unit run.
    // Browser-level coverage runs under Playwright, against the built app.
    exclude: ['**/node_modules/**', '**/dist/**', 'firestore/**', 'e2e/**'],
  },
})
